Website = "https://github.com/fcurrk/fetch-github-hosts"

[Details]
  Icon = "assets/public/logo.png"
  Name = "Fetch-Github-Hosts"
  ID = "com.github.fcurrk.fetch-github-hosts"
  Version = "2.6"
  Build = 58
