name: Build for Windows

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=v3.1.23.603" >> $GITHUB_ENV

      - name: Install Docker
        run: curl -fsSL https://get.docker.com | bash -s docker

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Go tidy
        run: go mod tidy

      - name: Install fyne-cross
        run: go get github.com/fyne-io/fyne-cross && go install github.com/fyne-io/fyne-cross

      - name: Package for Windows
        run: fyne-cross windows -arch=*

      - name: Create pkg dist dir
        run: mkdir pkg-dist

      - name: Move Windows-amd64
        run: mv fyne-cross/dist/windows-amd64/Fetch-Github-Hosts.exe.zip pkg-dist/fetch-github-hosts_windows_amd64.zip

      - name: Move Windows-386
        run: mv fyne-cross/dist/windows-386/Fetch-Github-Hosts.exe.zip pkg-dist/fetch-github-hosts_windows_386.zip

      - uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: |
            pkg-dist

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          append_body: true
          files: |
            pkg-dist/fetch-github-hosts_windows_amd64.zip
            pkg-dist/fetch-github-hosts_windows_386.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}